    version: 2.1
    executors:
      docker-publisher:
        environment:
          IMAGE_NAME: rohit6899/tracer1
        docker:
          - image: circleci/buildpack-deps:stretch
      ubuntu:
        docker:
          - image: ubuntu:16.04
    jobs:
      build:
        executor: docker-publisher
        steps:
          - checkout
          - setup_remote_docker
          - run: echo "export DATESTAMP=$(date +%Y%m%d)" > env-vars
          - run:
              name: Build Docker image
              command: |
                docker build -t $IMAGE_NAME:latest .
          - run:
              name: Archive Docker image
              command: docker save -o image.tar $IMAGE_NAME
          - persist_to_workspace:
              root: .
              paths:
                - ./image.tar
                - ./env-vars
      sysdig-secure:
        executor: ubuntu
        steps:
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "Whatsup"
                apt-get update
                echo "DING"
                apt-get -y install python-pip
                echo "DONG"
                pip install anchorecli
                anchore-cli image list
                echo "worked"
                anchore-cli image vuln docker.io/rohit6899/logdna-agent:latest all
                echo "wow"
      docker-hub:
        executor: docker-publisher
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - run: cat /tmp/workspace/env-vars >> $BASH_ENV
          - setup_remote_docker
          - run:
              name: Load archived Docker image
              command: docker load -i /tmp/workspace/image.tar
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                echo "$DATESTAMP"
                IMAGE_TAG=${CIRCLE_TAG/v/''}
                docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:$IMAGE_TAG
                docker tag $IMAGE_NAME:latest $IMAGE_NAME:${IMAGE_TAG}-${DATESTAMP}
                docker push ${IMAGE_NAME}:latest
                docker push $IMAGE_NAME:$IMAGE_TAG
                docker push $IMAGE_NAME:$IMAGE_TAG-${DATESTAMP}

      ibm-registry:
        executor: docker-publisher
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - setup_remote_docker
          - run:
              name: Load archived Docker image
              command: docker load -i /tmp/workspace/image.tar
          - run:
              name: Publish Docker Image to IBM registry
              command: |
                IMAGE_TAG=${CIRCLE_TAG/v/''}
                echo "${IBM_API_KEY}" | docker login -u iamapikey --password-stdin icr.io
                export DATESTAMP=$(date +%Y%m%d)
                echo "Hello World"            
    workflows:
      version: 2
      build-tags:
        jobs:
          - build:
              filters:
                tags:
                  only: /.*/
                branches:
                  ignore: /.*/
          - docker-hub:
              requires:
                - build
              filters:
                tags:
                  only: /.*/
                branches:
                  ignore: /.*/
          - ibm-registry:
              requires:
                - build
              filters:
                tags:
                  only: /.*/
                branches:
                  ignore: /.*/
          - sysdig-secure:
              filters:
                branches:
                  only: /.*/