    version: 2.1
    executors:
      docker-publisher:
        environment:
          IMAGE_NAME: rohit6899/tracer1
        docker:
          - image: circleci/buildpack-deps:stretch
      ubuntu:
        environment:
          IMAGE_NAME: rohit6899/tracer1
        docker:
          - image: ubuntu:16.04
    jobs:
      build:
        executor: docker-publisher
        steps:
          - checkout
          - setup_remote_docker
          - run: echo "export DATESTAMP=$(date +%Y%m%d)" > env-vars
          - run:
              name: Build Docker image
              command: |
                docker build -t $IMAGE_NAME:latest .
          - run:
              name: Archive Docker image
              command: docker save -o image.tar $IMAGE_NAME
          - persist_to_workspace:
              root: .
              paths:
                - ./image.tar
                - ./env-vars
      docker-hub:
        executor: docker-publisher
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - run: cat /tmp/workspace/env-vars >> $BASH_ENV
          - setup_remote_docker
          - run:
              name: Load archived Docker image
              command: docker load -i /tmp/workspace/image.tar
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
                IMAGE_TAG=1.2
                docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${IMAGE_TAG}-${DATESTAMP}
                docker push ${IMAGE_NAME}:${IMAGE_TAG}-${DATESTAMP}
      sysdig-secure:
        executor: ubuntu
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - run: cat /tmp/workspace/env-vars >> $BASH_ENV
          - setup_remote_docker
          - run:
              name: Load archived Docker image
              command: docker load -i /tmp/workspace/image.tar
          - run:
              name: Scan Image via Sysdig Secure.
              command: |
                apt-get update
                apt-get -y install python-pip
                pip install anchorecli
                IMAGE_TAG=1.2
                IMAGE=docker.io/${IMAGE_NAME}:${IMAGE_TAG}-${DATESTAMP}
                anchore-cli image add $IMAGE
                sleep 500
                anchore-cli image vuln $IMAGE
                OUTPUT="$(anchore-cli image vuln $IMAGE | grep High | wc -l)"
                if [ $OUTPUT -gt 0 ]; then exit 1; else exit 0; fi
      to-confirm:
        executor: ubuntu
        steps:
          - run:
              name: Test
              command: |
                echo "Victory"       
    workflows:
      version: 2
      build-tags:
        jobs:
          - build:
              filters:
                branches:
                  only: /.*/
          - docker-hub:
              requires:
                - build
          - sysdig-secure:
              requires:
                - docker-hub
          - to-confirm:
              requires:
                - sysdig-secure