    version: 2.1
    executors:
      docker-publisher:
        environment:
          IMAGE_NAME: logdna/logdna-agent
        docker:
          - image: circleci/buildpack-deps:stretch
    jobs:
      build:
        executor: docker-publisher
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Build Docker image
              command: |
                docker build -t $IMAGE_NAME:latest .
          - run:
              name: Archive Docker image
              command: docker save -o image.tar $IMAGE_NAME
          - persist_to_workspace:
              root: .
              paths:
                - ./image.tar
      docker-hub:
        executor: docker-publisher
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - setup_remote_docker
          - run:
              name: Load archived Docker image
              command: docker load -i /tmp/workspace/image.tar
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                export DATESTAMP=$(date +%Y%m%d)
                IMAGE_TAG=${CIRCLE_TAG/v/''}
                docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
                docker tag $IMAGE_NAME:latest $IMAGE_NAME:${IMAGE_TAG}-${DATESTAMP}
                docker push $IMAGE_NAME:latest
                docker push $IMAGE_NAME:$IMAGE_TAG
                docker push $IMAGE_NAME:$IMAGE_TAG-${DATESTAMP}
                
      ibm-registry:
        executor: docker-publisher
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - setup_remote_docker
          - run:
              name: Load archived Docker image
              command: docker load -i /tmp/workspace/image.tar
          - run:
              name: Publish Docker Image to IBM registry
              command: |
                echo "Hello World"            
    workflows:
      version: 2
      build-tags:
        jobs:
          - build:
              filters:
                tags:
                  only: /.*/
                branches:
                  ignore: /.*/
          - docker-hub:
              requires:
                - build
              filters:
                tags:
                  only: /.*/
                branches:
                  ignore: /.*/
          - ibm-registry:
              requires:
                - build
              filters:
                tags:
                  only: /.*/
                branches:
                  ignore: /.*/